-- ENUMS
CREATE TYPE gender_enum AS ENUM ('Male', 'Female', 'Other');
CREATE TYPE user_type_enum AS ENUM ('student', 'teacher', 'admin');

-- TABLES

CREATE TABLE "user" (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  middle_name VARCHAR(255) NOT NULL,
  birthdate DATE NOT NULL,
  gender gender_enum NOT NULL,
  type user_type_enum NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE subject (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  subject_name VARCHAR(150) NOT NULL,
  teacher_id INTEGER NOT NULL
);

CREATE TABLE student_code (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_id INTEGER NOT NULL,
  qrcode VARCHAR(255) NOT NULL,
  FOREIGN KEY (student_id) REFERENCES "user" (id)
);

CREATE TABLE student_subject (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  subject_id INTEGER,
  student_id INTEGER,
  FOREIGN KEY (subject_id) REFERENCES subject (id),
  FOREIGN KEY (student_id) REFERENCES "user" (id)
);

CREATE TABLE subject_attendance (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  subject_id INTEGER NOT NULL,
  student_id INTEGER NOT NULL,
  status VARCHAR(10) NOT NULL,
  date TIMESTAMP NOT NULL,
  FOREIGN KEY (subject_id) REFERENCES subject (id),
  FOREIGN KEY (student_id) REFERENCES "user" (id)
);

-- INSERT DATA

INSERT INTO "user" (id, first_name, last_name, middle_name, birthdate, gender, type, email, password) VALUES
(43, 'Super Admin', 'Super Admin', 'Super Admin', '1212-12-12', 'Male', 'admin', 'admin@email.com', 'admin'),
(70, 'T1 F', 'T1 F', 'T1 F', '2024-08-28', 'Female', 'teacher', 't1@t1.com', 't1'),
(71, 'S1', 'S1', 'S1', '2024-08-28', 'Male', 'student', 's1@s1.com', 's1');

INSERT INTO "subject" (id, subject_name, teacher_id) VALUES
(40, 'CCS-101', 70);

INSERT INTO "student_code" (id, student_id, qrcode) VALUES
(10, 71, '../images/S1_1724839653.png');

INSERT INTO "student_subject" (id, subject_id, student_id) VALUES
(28, 40, 71);

INSERT INTO "subject_attendance" (id, subject_id, student_id, status, date) VALUES
(18, 40, 71, 'Absent', '2024-08-28 18:11:49'),
(19, 40, 71, 'Present', '2024-08-29 18:13:21'),
(20, 40, 71, 'Present', '2024-08-27 18:14:03');